language: python

python:
    - "2.7"

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda/bin:$PATH

install:
    - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy pandas matplotlib pytables pytest
    - pip install lmfit
    - python setup.py build
    - python setup.py install
    - rm -rf build

before_script:
    - mkdir notebooks/data
    - cd notebooks/data
    - wget -N http://files.figshare.com/1839122/12d_New_30p_320mW_steer_3.hdf5
    - wget -N http://files.figshare.com/1839121/0023uLRpitc_NTP_20dT_0.5GndCl.hdf5
    - cd ../..

script:
    - py.test
