name: fretbursts-docs

channels:
- conda-forge
- default

dependencies:
- python=3.12
- setuptools
- matplotlib
- cython
- pytables
- lmfit
- mock
- pandas
- phconvert
- seaborn
- pip:
  - sphinx_bootstrap_theme
