name: fretbursts-docs

channels:
- conda-forge
- default

dependencies:
- python=3.12
- pip
- setuptools
- matplotlib
- cython
- pytables
- lmfit
- pandas
- phconvert
- mock
- sphinx
- pip:
  - seaborn
  - sphinx_bootstrap_theme
