name: fretbursts-docs

channels:
- conda-forge
- default

dependencies:
- python=3.8
- pip
- setuptools
- numpy
- matplotlib
- cython
- pytables
- lmfit
- mock
- pandas
- phconvert
- sphinx
- pip:
  - seaborn
  - sphinx_bootstrap_theme
