package:
  name: fretbursts
  version: {{ environ['GIT_DESCRIBE_TAG'] }}

source:
    #path: ../fretbursts/
    git_url: https://github.com/tritemio/fretbursts.git
    #git_tag : 0.4rc6.dev3

build:
    number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
    #string: {{ '0' if environ.get('GIT_BUILD_STR', '').startswith('0_') else environ.get('GIT_BUILD_STR', '') }}

requirements:
  build:
    - python
    - libpython    [win64 and py27]
    - setuptools
    - future
    - cython
    - numpy
    - scipy
    - mock
    - nose
    - matplotlib
    - seaborn
    - lmfit
    - phconvert

  run:
    - python
    - future
    - numpy
    - scipy
    - mock
    - nose
    - matplotlib
    - seaborn
    - pyqt
    - pytables
    - pandas
    - numba
    - lmfit
    - phconvert


test:
  # Python imports
  imports:
    - fretbursts
    - fretbursts.phtools.phrates

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/tritemio/FRETBursts/
  license: GPLv2
  summary: 'Burst analysis toolkit for single and multi-spot smFRET data.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
