package:
  name: fretbursts
  version: {{ environ['GIT_DESCRIBE_TAG'] }}

source:
    #path: ../fretbursts/
    git_url: https://github.com/tritemio/fretbursts.git
    #git_tag : 0.4rc6.dev3

build:
    number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
    #string: {{ '0' if environ.get('GIT_BUILD_STR', '').startswith('0_') else environ.get('GIT_BUILD_STR', '') }}

requirements:
  build:
    - python
    - setuptools
    - future
    - cython
    - numpy x.x
    - matplotlib
    - seaborn
    - lmfit
    - phconvert

  run:
    - python
    - future
    - numpy x.x
    - scipy
    - pyqt
    - matplotlib
    - seaborn
    - pandas
    - numba
    - lmfit
    - phconvert

test:
   imports:
    - fretbursts
    - fretbursts.phtools.phrates


about:
  home: http://github.com/tritemio/FRETBursts/
  license: GPLv2
  summary: 'Burst analysis software for single and multi-spot smFRET data.'
