name: Tests

on: 
  push:
    branch:
      - gitactions
  pull_request:
    branch:
      - gitactions
jobs:
  build:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{matrix.python-version}}
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest wheel cython numpy scipy pandas matplotlib numba nbconvert ipython seaborn tables phconvert lmfit pybroom
      - name: Install project
        run: |
          python setup.py sdist bdist_wheel
          pip install .
      - name: Download files
        run: |
          mkdir notebooks/data
          cd notebooks/data
          wget -N http://files.figshare.com/2182604/12d_New_30p_320mW_steer_3.hdf5
          wget -N http://files.figshare.com/2182601/0023uLRpitc_NTP_20dT_0.5GndCl.hdf5
          cd ../..
      - name: Test project
        run: |
          python fretbursts/tests/nbrun.py
          python -m pytest
